spring.application.name=DS_PROJECT
server.port=8080

#PGPASSWORD=gk9hcrBKhDyUo0ZAoAr58M3ynPdWi8bI psql -h dpg-ctjcv2rtq21c73e23c7g-a.oregon-postgres.render.com -U dsuser ds2024pv
spring.datasource.username=dsuser
spring.datasource.password=gk9hcrBKhDyUo0ZAoAr58M3ynPdWi8bI
spring.datasource.url=jdbc:postgresql://dpg-ctjcv2rtq21c73e23c7g-a.oregon-postgres.render.com:5432/ds2024pv

# auto generate sql and update db schema at startup
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update


#show and format sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#dialect
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
